version: '3.2'

services:
  server:
    image: httpd:2.4-alpine
    ports:
      - 8088:80
      #- 8443:443
    volumes:
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./apache/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
      - ./src:/usr/local/apache2/htdocs/
    depends_on:
      - php-fpm
      - database
    links:
      - php-fpm

  php-fpm:
    build:
      context: './php/'
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./src:/usr/local/apache2/htdocs/
      - ./src:/var/www/html
    environment:
      _DEBUG: 1

  database:
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql/custom:/etc/mysql/conf.d
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: example

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 3000:8080
    environment:
      ADMINER_DEFAULT_SERVER: database
